### ISSUE TITLE
Incoherent footnote content wrapping?

### ISSUE THREAD

**Issue by vhf** [syntax-tree/mdast-util-to-hast#14]
I think I found a bug but I was unable to track it down.

Input markdown:

```md
1 [^alpha bravo]

2 [^foo]

[^foo]: foobar
```

Then using

```javascript
// remark-parse with config:
{
  gfm: true,
  commonmark: false,
  footnotes: true
}
// then into 'remark-rehype'
// finally into 'rehype-stringify'
```

I get the following:

```diff
 <p>1 <sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup></p>
 <p>2 <sup id="fnref-foo"><a href="#fn-foo" class="footnote-ref">foo</a></sup></p>
 <div class="footnotes">
 <hr>
 <ol>
-<li id="fn-foo">
-<p>foobar</p>
 <a href="#fnref-foo" class="footnote-backref">↩</a>
 </li>
+<li id="fn-1">
+alpha bravo
 <a href="#fnref-1" class="footnote-backref">↩</a>
 </li>
 </ol>
 </div>
```

Highlighted is what might be considered a bug: `foobar` is wrapped in `p`, `alpha bravo` isn't.

**Comment by wooorm** [comment]
### Example

###### `example.md`

```markdown
1 [^alpha bravo]

2 [^foo]

[^foo]: foobar
```

###### `example.js`

```javascript
var vfile = require('to-vfile');
var report = require('vfile-reporter');
var unified = require('unified');
var markdown = require('remark-parse');
var remark2rehype = require('remark-rehype');
var html = require('rehype-stringify');

unified()
  .use(markdown, {footnotes: true})
  .use(remark2rehype)
  .use(html)
  .process(vfile.readSync('example.md'), function (err, file) {
    console.error(report(err || file));
    if (file) {
      file.extname = '.html';
      vfile.writeSync(file);
    }
  });
```

###### `example.html`

```html
<p>1 <sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup></p>
<p>2 <sup id="fnref-foo"><a href="#fn-foo" class="footnote-ref">foo</a></sup></p>
<div class="footnotes">
<hr>
<ol>
<li id="fn-foo">
<p>foobar</p>
<a href="#fnref-foo" class="footnote-backref">↩</a>
</li>
<li id="fn-1">
alpha bravo
<a href="#fnref-1" class="footnote-backref">↩</a>
</li>
</ol>
</div>
```

Here’s how that looks in a browser:

![screen shot 2017-08-12 at 10 03 01](https://user-images.githubusercontent.com/944406/29241345-7fa71bb0-7f45-11e7-96f0-9ef1878ac923.png)

### Why

The reason this happens is because a footnote definition (in this case, `foobar`) can contain blocks: block quotes, code, paragraphs, lists, etc. A normal footnote (in this case, `alpha bravo`) cannot: so the content is the same as the content of a paragraph.

### Conclusion

What do you expect should happen? Should the link in `#fn-foo` be added at the end of the `<p>`? Should the `<p>` be unwrapped? Should `#fn-1` have a `<p>`?

**Comment by vhf** [comment]
Yep, thanks!

I think I remember some discussion on the `remark` repo about lists were you were explaining why you decided to wrap `first level item` in a `p` in the following example:

```md
* first level item
    * 2nd level item
```

```html
<ul>
<li>
<p>first level item</p>
<ul>
<li>2nd level item</li>
</ul>
</li>
</ul>
```

I think the same should apply to `alpha bravo` in this issue example. Therefore I'd wrap it in a `p`.

**Comment by wooorm** [comment]
Thanks, I appreciate it btw!

Yes, mdast has a paragraph, even if the list-item is “inline-only”. That’s to make the `listItem` node the same, always. However, in HTML as your example shows that doesn’t always convert to a `<p>`.
With footnotes, they are two separate nodes, so they *can* differ.

You’re saying both footnotes should have a `<p>`, right? Why?

**Comment by vhf** [comment]
> You’re saying both footnotes should have a `<p>`, right? Why?

Almost, not exactly. I suggest to wrap every footnote content (`footnote` content and `footnoteDefinition` content) in a block-level html element. I think it would make sense because I believe that using the longhand syntax will always result in `footnoteDefinition` wrapped in a block-level element, while using the shorthand syntax (`footnote`) won't ever let you wrap the note in a block element.

`p` seems to be a reasonable choice to wrap `footnote`s.

For instance:

```md
a[^q]

[^q]: ![]()
```

gives

```html
<li id="fn-q">
<p><img src=""></p>
<a href="#fnref-q" class="footnote-backref">↩</a>
</li>
```

Without any styling, we then wouldn't see this rendering differences:

![](https://user-images.githubusercontent.com/944406/29241345-7fa71bb0-7f45-11e7-96f0-9ef1878ac923.png)

It might also ease the styling of `.footnotes > ol > li`s.

**Comment by wooorm** [comment]
@vhf Ahhhh sorry for the late reply!

From reading this again, I agree, we should do this!

Would you be interested in PRing?

**Comment by wooorm** [comment]
PS I added you to this org to make it easier to work together!

**Comment by vhf** [comment]
Cool! Yeah I'd be interested, I'll do my best!
