### ISSUE TITLE
Having issues rendering table content.  Converts all children to divs.

### ISSUE THREAD

**Issue by ozymandias547** [syntax-tree/mdast-util-to-hast#17]
Is this utility suppose to convert inner table contents properly?

**Comment by wooorm** [comment]
Yes, it is supposed to work. This issue is probably related to some other part of your code. Please check the [`contributing.md` doc](https://github.com/syntax-tree/mdast/blob/master/contributing.md#submitting-an-issue) on how to create specific, actionable issues!

**Comment by ozymandias547** [comment]
ok, I verified that "tableCell" and "tableRow" don't exist in the handlers, so they are defaulting to "divs".  Is this worth a pull request or am i missing something?

**Comment by ozymandias547** [comment]
Scratch that! I found out that the issue was with my pipe transformer.  My bad.

**Comment by wooorm** [comment]
OK, good! Thanks for checking, @ozymandias547!
