### ISSUE TITLE
I'm attempting to write a plugin that will allow me to embed custom JSX tags into markdown and subsequently render

### ISSUE THREAD

**Issue by mrpotatoes** [syntax-tree/mdast-util-to-hast#18]
I'm coming up against issues and I know to where I am failing.

The `mdast` tree needs to get converted to an `hast` tree but any custom nodes are replaced with `div` nodes. I'm looking to allow any custom nodes (like XML).

How can I make this possible?

**Comment by mrpotatoes** [comment]
I was able to get it to work by modifying line [78 in `lib/index.js`](https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/index.js#L78) to: `tagName: node.tagName || tagName,`

If it is converted to this then I can do what I need. I'm thinking that this isn't going to be an option for you but it'll work nicely for my plugin and I'll just make a copy of this code with the custom modification. If in the future you do make that an option I would be thrilled!

**Comment by wooorm** [comment]
Hey Andric! This is described in the [notes](https://github.com/syntax-tree/mdast-util-to-hast#notes), specifically, use `node.data.hName` to set tag names on MDAST nodes for use in HAST!
Does that help? Comment if not, and I’ll re-open this issue!

**Comment by mrpotatoes** [comment]
Excellent, I'll give that a look when I get home tonight!
