### ISSUE TITLE
Full reference links should have a fallback

### ISSUE THREAD

**Issue by rubys** [syntax-tree/mdast-util-to-hast#20]
Background: I'm converting node.js from marked to unified/remark/rehype, and found a regression.  It seems that mdast-util-to-hast intentionally does not have a fallback for link references:

https://github.com/syntax-tree/mdast-util-to-hast/blob/f2e3ec5fc6476c3628a85cd07456c14d1e887c61/test/link-reference.js#L22-L44

This varies from the commonmark spec and other implementations:

https://spec.commonmark.org/0.28/#full-reference-link
https://spec.commonmark.org/dingus/?text=[foo][bar]

Is there a reason for this deviation?

**Comment by wooorm** [comment]
@rubys Sorry for the slow reply!

The reason that this isn’t represented in the AST is that it is based on the output. Markdown stringifies those differently than HTML.

However, if `mdast-util-to-hast` produces an AST that’s stringified differently than how commonmark/github does it, it’s a bug. It shouldn’t deviate, and I welcome a PR!

**Comment by rubys** [comment]
`mdast-util-to-hast` does indeed produce an AST that is stringified differently than how commonmark/github does it.  You can quickly verify this by entering `[foo][bar]` in the [commonmark dingus page](https://spec.commonmark.org/dingus/).

A PR, with updated test cases can be found at https://github.com/syntax-tree/mdast-util-to-hast/pull/21

**Comment by wooorm** [comment]
Oh sorry, missed it!

**Comment by rubys** [comment]
Thanks!  It looks like I will have a follow-on issue that will require a slightly bigger change (not so much in terms of lines of code, but affecting not only docs, but also a small change to `remark-rehype`).

The issue is that remark-parse's mdast tree for potential link or image reference is lossy... for example, the identifier is converted to lowercase.

The fix I suggest is that callers to `mdast-util-to-hast` can _optionally_ pass the file.contents as an option.  If that option is present, **and** position information is present, **and** an undefined reference is encountered, **then** the undefined reference will be replaced with the original text from the file contents. If any one of these conditions is not met, the current fallback logic will be used.

Thoughts?

**Comment by wooorm** [comment]
In fine discussing this! It does sound like a lot of logic, couldn't we perhaps add a new 'reference' property to references that define the value that was used, next to reference type?
The downside is that this could result in inconsistent trees, but maybe we could work around that somehow?

**Comment by rubys** [comment]
Three pull requests ready for review:

 * https://github.com/syntax-tree/mdast/pull/23
 * https://github.com/remarkjs/remark/pull/346
 * https://github.com/syntax-tree/mdast-util-to-hast/pull/22
