### ISSUE TITLE
Add `options.html5` to convert valid html5

### ISSUE THREAD

**Issue by nzt** [syntax-tree/mdast-util-to-hast#43]
This issue is continuations of [that discussion](https://spectrum.chat/unified/syntax-tree/mdast-util-to-hast-converts-mdast-to-invalid-hast~3ebdd2c9-d2ab-4722-9857-e266524d65b5)

Hi there, I report inconsistency between hast and GFM specification. table syntax of GFM will translate table elements together with align attribute, which is obsolete attribute in HTML5. I guess hast is designed with respect to HTML5 specification, but mdast-util-to-hast converts markdown document to obsolete HTML document because of align attribute. It is out of the original concept of hast, isn't it? This is not a bug of mdast-util-to-hast, although I'd like to make a new option for HTML5 compatible mode like data-align="center"
Which should we choose, GFM or HTML5? Could we ignore W3C?

This is reproducible code.
```js
const unified = require("unified")
const remark = require("remark-parse")
const remark2rehype = require("remark-rehype")
const stringify = require("rehype-stringify")
const src = `
| a | b | c |
|:--|:-:|--:|
| d | e | f |
`
unified()
    .use(remark)
    .use(remark2rehype)
    .use(stringify)
    .process(src, (err, file) => {
        console.log(file.toString())
    })
```

The above code yields:

```html
<table>
<thead>
<tr>
<th align="left">a</th>
<th align="center">b</th>
<th align="right">c</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">d</td>
<td align="center">e</td>
<td align="right">f</td>
</tr>
</tbody>
</table>
```

In the fact, we had to use third party option https://github.com/mapbox/hast-util-table-cell-style to solve this issue. @ChristianMurphy said

> It looks like rehype-react is using https://github.com/mapbox/hast-util-table-cell-style to do the conversion.
> I'd be open to having this be a native part of rehype, thoughts  @wooorm ?

**Comment by wooorm** [comment]
> I report inconsistency between hast and GFM specification.

GFM specifies `align`, and we use that too. How is that inconsistent?

> It is out of the original concept of hast, isn't it

Previously we had several HTML standards. Some from W3C, and HTML5 from WHATWG. WHATWG stopped versioning their specification and called it: HTML, the living standard. Then there was W3C copy-pasting the work from WHATWG and calling it HTML5.1, HTML5.2, etc. But now they stoped. There is just one HTML.
The goal of hast is to reflect HTML (the living standard).

HTML has several things that are “obsolete”, but obsolete means that *authors* shouldn’t use them. But that user agents should still support them.

While GFM depends on obsolete features, those features are still HTML. The current behavior conforms to both the GFM and the HTML specifications.

---

Now, React for example doesn’t like those attributes and warns for them. So there is a utility to change them to `style="text-align:..."`.
What is your reason to not prefer those attributes?

**Comment by nzt** [comment]
I see. You are right as:

> The following attributes are obsolete (**though the elements are still part of the language**), and must not be used by authors: (quoted from https://dev.w3.org/html5/pf-summary/obsolete.html)

Excuse me, I have skipped to read the above comments in HTML specification, but I have read it just now and so I correct it to that this package generate still HTML.

> HTML has several things that are “obsolete”, but **obsolete means that authors shouldn’t use them**. But that user agents should still support them.

We also should not use them, shouldn't us? Markdown-It is so.
I know several Markdown interpreter still uses obsoleted feature to follow commonly used markdown flavor, GFM. I propose to make an *option*, which is not default behavior.

> What is your reason to not prefer those attributes?

Let me show this example.

```htm
<!-- html -->
<table>
  <thead>
    <th style="text-align: left">a</th>
    <th style="text-align: left">b</th>
  </thead>
  <tbody>
    <td align="left">x</td>
    <td align="left">y</td>
  </tbody>
</table>l
```

```css
/* stylesheet */
th, td {
  text-align: center;
  width: 50px;
  border: 1px solid black;
}
```

If we use `align` attribute like `x` and `y`, stylesheet will overwrite this format, i.e., `x` and `y` are placed at the center of cell.
On the other hand, if we use `style` attribute like `a` and `b`, this attribute overwrite the stylesheet, i.e., `a` and `b` are placed at the left of cell.

If we use some css frameworks, the frameworks forced to alignment of cell even if we declared it in markdown.

https://github.com/franciscop/picnic/blob/731b74140c8ab787d7aa30ec14fa8c637e2dda5d/src/plugins/table/_plugin.scss#L10-L15

The css framework can ignore obsoleted feature because it was obsoleted.
Ignoring obsoleted features versus using obsoleted features, I feel that first one is better decision for world wide web.

**Comment by wooorm** [comment]
To solve this with css, you can do two things:

Force `align` to be used:

```css
[align=left] { text-align: left }
```

Or apply the text-style on a parent, such as:

```css
table { text-align: center }
```

---

It’s unfortunate that Picnic applies the alignment on cells! It *also* does that on the `<table>` already, not sure why it’s duplicated! Maybe a bug there?

---

> We also should not use them, shouldn't us? Markdown-It is so.
> I know several Markdown interpreter still uses obsoleted feature to follow commonly used markdown flavor, GFM. I propose to make an option, which is not default behavior.

And what would that option use? Classes (`.left`, `.align-left`, `.text-align-left`)? Or inline styles (`style=text-align:left`)?

It seems there are several options, and then maybe it’s better to do it in userland, such as [`mapbox/hast-util-table-cell-style`](https://github.com/mapbox/hast-util-table-cell-style)? Or is there a really good single alternative?

**Comment by nzt** [comment]
Let me show one more example commonly happened. If bootstrap was loaded on the website, your second suggestion still does not work. https://jsfiddle.net/jrdyw6cu/31/

```scss
/*  https://github.com/twbs/bootstrap/blob/master/scss/_reboot.scss */
// 1. Matches default `<td>` alignment by inheriting `text-align`.
// 2. Fix alignment for Safari

th {
  text-align: inherit; // 1
  text-align: -webkit-match-parent; // 2
}
```

Thus We should use `[align=left] { text-align: left }`.

- - -

I agree with you. There are so many options we could consider, but using obsoleted features is not a better way than others. We choose one, and also user provides others of them in userland. I guess this option makes community healthy. At this point of view, I offer to use `style` attribute like `@mapbox/hast-util-table-cell-style`, `markdown-it`.

**Comment by wooorm** [comment]
For a solution, should we add another [note](https://github.com/syntax-tree/mdast-util-to-hast#notes)?:

```
*   The obsolete `align` is added on `td` and `th` elements, combine with
    [`@mapbox/hast-util-table-cell-style`](https://github.com/mapbox/hast-util-table-cell-style)
    later to use `style` instead

**Comment by nzt** [comment]
I see. I have no  more idea that is acceptable for you. It is the best solution except adding HTML5 option. Please add the note to README. Thank you for the discussion with me.

**Comment by wooorm** [comment]
Yeah, I think it’s best to stick exactly with how GitHub does it: tables and task lists for example, are GFM features. It’s possible to change it with a small plugin such as `hast-util-table-cell-style`, so it isn’t a *huge* inconvenience.

**Comment by wooorm** [comment]
Thanks for the discussion @nzt! 🤗
