### ISSUE TITLE
all, one, etc should be re-exported in main index.js?

### ISSUE THREAD

**Issue by ignatiusreza** [syntax-tree/mdast-util-to-hast#53]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Subject

The exported `toHast` support passing `options.handlers` to provide customized logic to process certain node. The documentation for this options suggest to "Take a look at `lib/handlers/` for examples.".

Most of the handlers under `lib/handlers/` are written using the helper function `all`, `one`, etc. So it seems quite reasonable for custom handlers to also want to use those helper functions.

### Problem

Pre-ESM migration, we can import/require directly from `mdast-util-to-hast/lib/all` and it will worked.

Post-ESM migration, `.mjs` file can't import from `mdast-util-to-hast/lib/all.js` since it is written using esm syntax, but does not have `.mjs` extension (seems like for direct file import, the `type: module` config in `package.json` is ignored?)

### Solution

in `index.js`, we should reexport the helper functions

```js
export {all} from './lib/all.js'
export {one} from './lib/one.js'
export {toHast} from './lib/index.js'
```

so that we can import it like `import { all, toHash } from 'mdast-util-to-hast';`..

### Alternatives

Copy+paste the helper functions?

**Comment by wooorm** [comment]
> Post-ESM migration, .mjs file can't import from mdast-util-to-hast/lib/all.js since it is written using esm syntax, but does not have .mjs extension (seems like for direct file import, the type: module config in package.json is ignored?)

It should work. It sounds like your tooling or project isn’t set up to support ESM?

**Comment by wooorm** [comment]
That being said, exporting them from `index.js` is probably a good idea! Is that something you can work on? (adding some docs for them would be needed too)
