### ISSUE TITLE
Circular dependencies break rollup build

### ISSUE THREAD

**Issue by SQReder** [syntax-tree/mdast-util-to-hast#55]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: 11.1.0

### Steps to reproduce

1. Use rollup for bundle project with some lib that use mdast-util-to-hast
2. Build project

Link to code example: 

I've extracted mdast-util-to-hast into separate chunk to easy inspection. The produced code (in `build` directory) unable to be bunded in correct direction in reason of circular deps

https://github.com/SQReder/cautious-pancake/blob/main/build/hast-ea6dff5f.js#L334-L384

```js
var one$5 = one_1; // ❗ capture one$5 as undefined

function all$g(h, parent) {
  var nodes = parent.children || [];
  var length = nodes.length;
  var values = [];
  var index = -1;
  var result;
  var head;

  while (++index < length) {
    result = one$5(h, nodes[index], parent); // ❗❗ TypeError: one$5 is not a function

    if (result) {
      if (index && nodes[index - 1].type === 'break') {
        if (result.value) {
          result.value = result.value.replace(/^\s+/, '');
        }

        head = result.children && result.children[0];

        if (head && head.value) {
          head.value = head.value.replace(/^\s+/, '');
        }
      }

      values = values.concat(result);
    }
  }

  return values
}

var one_1 = one$4; // ❗ declaration hoists, but initialization not

var u$b = unistBuilder;
var all$f = all_1$1;

var own$6 = {}.hasOwnProperty;

// Transform an unknown node.
function unknown(h, node) {
  if (text$3(node)) {
    return h.augment(node, u$b('text', node.value))
  }

  return h(node, 'div', all$f(h, node))
}

// Visit a node.
function one$4(h, node, parent) { // ❗ function declaration will hoist 
...
```

Also code from current project (non-minified)
![image](https://user-images.githubusercontent.com/1519753/121178969-cc515100-c867-11eb-9008-cca8b5ac16ab.png)

### Expected behavior

Expect code to be working

### Actual behavior

Circular deps prevent code to be correctly bundled

**Comment by wooorm** [comment]
Good idea, PRs welcome!

**Comment by wooorm** [comment]
Released in https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/11.1.1!

**Comment by wooorm** [comment]
No, I’m not maintaining multiple release lines — perhaps for security issues, but this isn’t one.
In a couple of weeks I’ll update `remark-rehype`, on the road to update the ecosystem (https://github.com/unifiedjs/unified/issues/121).
`remark-rehype` is quite a small wrapper, you could perhaps copy/paste the relevant bits into your code for now, or: maybe there’s a way around this in Rollup, because I am assuming many more users would’ve run into this for such a highly-downloaded project otherwise.

**Comment by SQReder** [comment]
The target package which I use on the project is `react-markdown`, so it's not straightforward to use this fix. I can't just override version of `mdash-util-to-hast` because of breaking changes ¯\(°_o)/¯

```
$ npm ls mdast-util-to-hast
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
basic-ui@0.1.0
+-- @storybook/addon-essentials@6.2.9
| `-- @storybook/addon-docs@6.2.9
|   `-- @mdx-js/mdx@1.6.22
|     `-- mdast-util-to-hast@10.0.1
`-- react-markdown@6.0.2
  `-- remark-rehype@8.1.0
    `-- mdast-util-to-hast@10.2.0
```

**Comment by wooorm** [comment]
I can’t imagine you’re the only Rollup user using `react-markdown`, `remark-rehype`, or `mdast-util-to-hast`, I’m assuming there are ways around this?

**Comment by SQReder** [comment]
Fair enough, but I don't see any workarounds, at least now. Can I do something to make `remark-rehype` release sooner?

**Comment by wooorm** [comment]
I’m sorry, I don’t see any workarounds other than configuring Rollup to support them, or using alternate tools, either

**Comment by SQReder** [comment]
I've published a patched version of 10.2.1 with custom name and aliased it in the bundler configuration

**Comment by nickarora** [comment]
This exact issue is causing issues for us; It's now been about 8 weeks since it was first reported...can we expect any progress soon?

**Comment by wooorm** [comment]
I believe what you’re looking for can be found in this thread. Do you have any new insights?

> can we expect any progress soon?

Can we expect any money soon? 🤷‍♂️

Perhaps of interest: https://github.com/syntax-tree/mdast-util-to-hast/blob/b84a13fc608dca453f48828f5e4daef5ff694ad1/license#L16.

**Comment by SQReder** [comment]
Despite the lack of guarantees, there is no reason to be rude. You could have taken in account that the problem manifests itself for many users, and issue a patch release, but you by some reason prefer not to do it.

If it's a question of money, you can just name a price instead of being smart alec 🤦🏻‍♂️

**Comment by nickarora** [comment]
@wooorm I wasn't intending to be snarky; my question was based on your above statement from June 8th

> In a couple of weeks I’ll update remark-rehype

Based on your assurance, it was a reasonable question to ask.  Also, based on your response, I suspect the answer is that your earlier statement was optimistic and there is unlikely to be a change to the status quo any time soon.  I'm not sure what money has to do with it.

**Comment by wooorm** [comment]
The work on moving hundreds of repos over to ESM is still ongoing. The good news is that only the remark and rehype organizations are left. So that’s pretty soon (±next week).

> I'm not sure what money has to do with it.

You mentioned expectations. And talked from “we”. That sounds to me like a company with expectations.

**Comment by nickarora** [comment]
@wooorm "we" --- as in the downstream users affected by this bug...You are projecting your own personal issues/grievances into this thread...and it was really just a simple question.
