### ISSUE TITLE
Add option to autoclose tags, for example, <hr> or <img>

### ISSUE THREAD

**Issue by teinett** [syntax-tree/mdast-util-to-hast#57]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

There are issues with tags that don't have closing tags. For example,`<hr>` and`<img>`.

In some cases we need to use it with autoclosing: 
`<hr>` => `<hr />`
`<img>` => `<img />`

Does the plugin have the option to add this slash symbol?

### Solution

My code now, for example:
```
import unified from 'unified';
import markdown from 'remark-parse';
import remark2rehype from 'remark-rehype';
import html from 'rehype-stringify';
import raw  from 'rehype-raw';
import sanitize from 'rehype-sanitize';
import remarkTypograf from '@mavrin/remark-typograf';


const content = unified()
    .use(markdown)
    .use(remarkTypograf, { locale: ["ru"] })
    .use(remark2rehype, {allowDangerousHtml: true})
    .use(raw)
    .use(sanitize)
    .use(html)
    .processSync(input)
    .toString()
```

It would be nice to have option: `.use(remark2rehype, {allowDangerousHtml: true, autoCloseTags: true})`

### Alternatives

I didn't find any yet.

**Comment by wooorm** [comment]
The options for formatting html can be passed to rehype-stringify: https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify#api.

What type of issues are you experiencing? All html parsers support these tags w/o that slash

**Comment by ChristianMurphy** [comment]
Hey @teinett! :wave: 
A good question, this plugin specifically works with abstract syntax trees, meaning it has the structure of the document, but not the exact HTML syntax that will be used.
`rehype-stringify` handles that, and has a self closing option https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify#use

**Comment by teinett** [comment]
@wooorm @ChristianMurphy You are awesome! Thank you!
