### ISSUE TITLE
Inefficient regex in text handler

### ISSUE THREAD

**Issue by 42shadow42** [syntax-tree/mdast-util-to-hast#61]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-hast@12.1.1

### Link to runnable example

https://codesandbox.io/s/remark-rehype-recursion-limits-forked-wlhoku?file=/src/index.js

### Steps to reproduce

In investigating resolutions to a trim "vulnerability" in our project we determined it was vulnerable to a DOS attack in some sense. In cases where an attacker provides a particular payload it can cause slowdowns, or errors in parsing and transforming markup. Reproduction is simple. In markdown representation include a text node with an excessive count of tabs and spaces with no line endings between.

### Expected behavior

The processing should occur in linear time.

### Actual behavior

The processing occurs in an escalating curve.

### Affected runtime and version

node@18.2 or executed in a browser context

### Affected package manager and version

npm@8.9.0

### Affected OS and version

macOS Monterey 12.3.1

**Comment by 42shadow42** [comment]
It works, but it changes the nature of the regex, in the example above the regex is a very slow no-op. In the regex I provided above it trims a bunch of whitespace, before I create I PR I wanted to confirm the expectations for the regex were acceptable.

**Comment by wooorm** [comment]
There's a lot of tests. If it works, it most like works

**Comment by 42shadow42** [comment]
The tests passed, but it still didn't sit right to me to have a behavior change so with some peers we came up with a better idea that should be equivalent, but faster. It breaks the regex into two parts one to remove trailing whitespace, one to remove leading whitespace, this prevents the rewind issue in the original regex. I'll open up a PR shortly.
