### ISSUE TITLE
Regression in 12.2.3: urls are escaped twice

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-to-hast#67]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-hast@v12.2.3

### Steps to reproduce

the changes in [#f21c1b112b7e1507a098d9a7812068f4b4913e31](https://github.com/syntax-tree/mdast-util-to-hast/commit/f21c1b112b7e1507a098d9a7812068f4b4913e31) introduce a regression, such as urls are escaped twice.

the following md:

```markdown
![](https://foo.com/media_10ea15e05c418d85e87762fa60afb9942a4d4ca1e.png#width=32\&height=32)
```

is rendered as follows with 12.2.3:

```html
<img src="https://foo.com/media_10ea15e05c418d85e87762fa60afb9942a4d4ca1e.png#width=32&#x26;amp;height=32">
```

but was correct with 12.2.2:

```html
<img src="https://foo.com/media_10ea15e05c418d85e87762fa60afb9942a4d4ca1e.png#width=32&#x26;height=32">
```

### Expected behavior

the urls should be properly escaped

### Actual behavior

the urls are escaped twice

### Affected runtime and version

node 16

**Comment by wooorm** [comment]
thanks, released in 12.2.4!
